version: "3"
services:
  rain_ows:
    restart: unless-stopped
    build: .
    image: rain_ows
    container_name: rain_wps_1
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./wps/pywps/:/opt/pywps
      - ./wps/log/:/var/log/pywps
      - ./wps/grass_data/:/opt/grass_location
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
